language: android
android:
  components:
    # The BuildTools version used by your project (make sure it's exactly the same as in the build.gradle)
    - build-tools-29.0.3
    # The SDK version used to compile your project
    - android-29
    # The SDK version used by the system image
    - android-22
    # The system image, to run an emulator during the tests
    - sys-img-armeabi-v7a-android-22

sudo: required


env:
    global:
    #minutes (2 minutes by default), prevents CommandShellUnresponsiveExceptions
    - ADB_INSTALL_TIMEOUT=14

    # setup of emulators this will be tested on
    #
    # API:         Desired API level of the emulator
    # ANDROID_ABI: Currently either "armeabi" (only needed for API8) or "armeabi-v7a"
    # ANDROID_TAG: Either "default" or "google_apis" if play services are used
    #
    # Below list was generated in June 2018. To get an up to date list of available options run "sdkmanager --list"
    #
    # Note: Currently (June 2018) there are no arm images for API > 25 provided by google.
    #       This is unlikely to change in the future due to the new emulator supporting
    #       (and requiring!) hardware acceleration for x86.
    #       Unfortunately Travis has no solution yet for providing KVM on the worker machines
    #       so running API25 and up emulators is not possible right now.
    
    matrix:
    #- API=10 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=10 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=14 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default         # emulator consistently times out
    #- API=15 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default         # https://github.com/osmdroid/osmdroid/issues/1066
    #- API=15 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=16 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=17 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=17 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=18 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=18 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=19 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=21 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default
    #- API=21 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=22 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default         # com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_DEXOPT: Package couldn't be installed in /data/app/org.osmdroid-2: scanPackageLI
    - API=22 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # currently no google apis needed
    #- API=23 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default         # sdkmanager --list reports this to be available, but image is not found during build
    #- API=23 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # Unable to install /home/travis/build/cbalster/osmdroid/OpenStreetMapViewer/build/outputs/apk/OpenStreetMapViewer-6.0.2-SNAPSHOT-debug.apk com.android.ddmlib.InstallException: Failed to establish session
    #- API=24 ANDROID_ABI=armeabi-v7a ANDROID_TAG=default         # "The command "adb shell ls /" failed and exited with 1 during." see line 108
    #- API=24 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # emulator consistently times out
    #- API=25 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis     # no addons available, so can't be used

before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
  # Set up Code Climate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./gradlew build connectedCheck jacocoTestReport
after_script:
  # Report test coverage to Code Climate
  - export JACOCO_SOURCE_PATH=app/src/main/java/
  - ./cc-test-reporter format-coverage ./app/build/reports/coverage/debug/report.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
